echo "*****************************************************"
echo "learning-modules-prod-web-1"
echo "*****************************************************"
ssh root@learning-modules-prod-web-1 "tail -100 /var/log/httpd/learning-modules-ssl-access_log | grep -v 18.9.42.11 | grep -v 18.9.42.41"
echo "*****************************************************"
echo "gradebook-prod-app-1"
echo "*****************************************************"
ssh root@gradebook-prod-app-1 "tail -100 /usr/local/tomcat/logs/catalina.out"
echo "*****************************************************"
echo "learning-modules-prod-web-2"
echo "*****************************************************"
ssh root@learning-modules-prod-web-2 "tail -100 /var/log/httpd/learning-modules-ssl-access_log | grep -v 18.9.42.11 | grep -v 18.9.42.41"
echo "*****************************************************"
echo "gradebook-prod-app-2"
echo "*****************************************************"
ssh root@gradebook-prod-app-2 "tail -100 /usr/local/tomcat/logs/catalina.out"
